name: Update image version

on:
  repository_dispatch:
    types: [new-image-version]

jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.BOT_TOKEN }}
      - name: Update version
        run: bin/update_version ${{ github.event.client_payload.repository }} ${{ github.event.client_payload.image_version }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.BOT_TOKEN }}
          commit-message: Update ${{ github.event.client_payload.repository }} image version to ${{ github.event.client_payload.image_version }}
          title: Update ${{ github.event.client_payload.repository }} image version to ${{ github.event.client_payload.image_version }}
          labels: automation
          branch: update-image-version
          branch-suffix: short-commit-hash
          reviewers: phss
